{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "shopmart",
    "contact": {}
  },
  "host": "node-app-demo-first.herokuapp.com",
  "basePath": "/api",
  "schemes": [
    "https",
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/product/get": {
      "get": {
        "summary": "get product",
        "tags": [
          "product"
        ],
        "operationId": "getproduct",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/product/post": {
      "post": {
        "summary": "post product",
        "tags": [
          "product"
        ],
        "operationId": "postproduct",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "parameters": [
          {
            "name": "shopName",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "price",
            "in": "formData",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "offerPrice",
            "in": "formData",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "discount",
            "in": "formData",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "productName",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "rating",
            "in": "formData",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "category",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "productImage",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/product/delete": {
      "delete": {
        "summary": "delete product",
        "tags": [
          "product"
        ],
        "operationId": "deleteproduct",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/product/update": {
      "post": {
        "summary": "update product",
        "tags": [
          "product"
        ],
        "operationId": "updateproduct",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/updateproductrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/product/getById": {
      "get": {
        "summary": "getByID product",
        "tags": [
          "product"
        ],
        "operationId": "getByIDproduct",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/user/get": {
      "get": {
        "summary": "user get",
        "tags": [
          "user"
        ],
        "operationId": "userget",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/user/register": {
      "post": {
        "summary": "user register",
        "tags": [
          "user"
        ],
        "operationId": "userregister",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/userregisterrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/user/login": {
      "post": {
        "summary": "user login",
        "tags": [
          "user"
        ],
        "operationId": "userlogin",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/userloginrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/activateAccount": {
      "post": {
        "summary": "active user",
        "tags": [
          "user"
        ],
        "operationId": "activeuser",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/activeuserrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/user/forgetpassowrd": {
      "post": {
        "summary": "forget password",
        "tags": [
          "user"
        ],
        "operationId": "forgetpassowrd",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/forgetpasswordrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/user/verifyOtpCode": {
      "post": {
        "summary": "verify otp",
        "tags": [
          "user"
        ],
        "operationId": "verifyotp",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/verifyotprequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/user/changePassword": {
      "post": {
        "summary": "change password",
        "tags": [
          "user"
        ],
        "operationId": "changepassword",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/changepasswordrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    }
  },
  "definitions": {
    "updateproductrequest": {
      "title": "updateproductrequest",
      "example": {
        "id": "62a6ae834f8eef1124e25782",
        "shopName": "new shop",
        "productImage": "formdata image",
        "price": 13245,
        "offerPrice": 15000,
        "discount": 20,
        "productName": "new",
        "rating": 50,
        "category": "shoes"
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "shopName": {
          "type": "string"
        },
        "productImage": {
          "type": "string"
        },
        "price": {
          "type": "integer",
          "format": "int32"
        },
        "offerPrice": {
          "type": "integer",
          "format": "int32"
        },
        "discount": {
          "type": "integer",
          "format": "int32"
        },
        "productName": {
          "type": "string"
        },
        "rating": {
          "type": "integer",
          "format": "int32"
        },
        "category": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "shopName",
        "productImage",
        "price",
        "offerPrice",
        "discount",
        "productName",
        "rating",
        "category"
      ]
    },
    "userregisterrequest": {
      "title": "userregisterrequest",
      "example": {
        "userName": "demo user",
        "email": "demo@gmail.com",
        "mobile": "5345136137",
        "password": "123456",
        "confirmPassword": "123456"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": [
        "userName",
        "email",
        "mobile",
        "password",
        "confirmPassword"
      ]
    },
    "userloginrequest": {
      "title": "userloginrequest",
      "example": {
        "email": "demo@gmail.com",
        "password": "123456"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": [
        "email",
        "password"
      ]
    },
    "activeuserrequest": {
      "title": "activeuserrequest",
      "example": {
        "email": "demo@gmail.com",
        "accountActivationCode": "123456"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "accountActivationCode": {
          "type": "string"
        }
      },
      "required": [
        "email",
        "accountActivationCode"
      ]
    },
    "forgetpasswordrequest": {
      "title": "forgetpasswordrequest",
      "example": {
        "email": "demo@gmail.com"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        }
      },
      "required": [
        "email"
      ]
    },
    "verifyotprequest": {
      "title": "verifyotprequest",
      "example": {
        "email": "demo@gmail.com",
        "otpCode": "123456",
        "newPassword": "demo@123",
        "confirmPassword": "demo@123"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "otpCode": {
          "type": "string"
        },
        "newPassword": {
          "type": "string"
        },
        "confirmPassword": {
          "type": "string"
        }
      },
      "required": [
        "email",
        "otpCode",
        "newPassword",
        "confirmPassword"
      ]
    },
    "changepasswordrequest": {
      "title": "changepasswordrequest",
      "example": {
        "email": "demo@gmail.com",
        "oldPassword": "demo@123",
        "newPassword": "demo@new",
        "confirmPassword": "demo@new"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "oldPassword": {
          "type": "string"
        },
        "newPassword": {
          "type": "string"
        },
        "confirmPassword": {
          "type": "string"
        }
      },
      "required": [
        "email",
        "oldPassword",
        "newPassword",
        "confirmPassword"
      ]
    }
  },
  "tags": [
    {
      "name": "product"
    },
    {
      "name": "user"
    }
  ]
}